vinrec/models/release_information.py
# Global imports
import requests
import peewee

# Local imports
from vinrec.util.database import Database

# Objects containing metadata
class ReleaseInfo(peewee.Model):

    rid = peewee.TextField()
    is_external = peewee.BooleanField(default=False)
    is_edited = peewee.BooleanField(default=False)

    artist = peewee.TextField()
    title = peewee.TextField()
    genres = peewee.TextField()
    released = peewee.IntegerField()

    cover_image = peewee.TextField(null=True) # filename of cover image

    def get_tracks(self):
        return TrackInfo.select().where(TrackInfo.release==self).objects()

    def get_images(self):
        return ImageInfo.select().where(ImageInfo.release==self).objects()

    def get_genres(self):
        return self.genres.split(";")

    class Meta:
        database = Database.get()

class TrackInfo(peewee.Model):

    duration = peewee.IntegerField()
    side = peewee.CharField(max_length=1)
    position = peewee.IntegerField()
    title = peewee.TextField()

    release = peewee.ForeignKeyField(ReleaseInfo)

    class Meta:
        database = Database.get()

class ImageInfo(peewee.Model):

    thumb = peewee.TextField()
    full = peewee.TextField()
    iid = peewee.CharField()

    release = peewee.ForeignKeyField(ReleaseInfo)

    class Meta:
        database = Database.get()

# Cache release objects
class ReleaseCache(object):

    @staticmethod
    def get(rid):
        return ReleaseInfo.get_or_none(ReleaseInfo.rid==rid)

    @staticmethod
    def add(object, cid=None):
        pass

vinrec/views/release_information.py
# Flask imports
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import url_for
from flask import request
from flask import abort

# Global imports
import os
import copy
import uuid

# Local imports
from vinrec.util.discogs import search
from vinrec.util.discogs import SearchResultCache
from vinrec.util.discogs import load_release_info
from vinrec.util.discogs import store_cover
from vinrec.models.release_information import ReleaseCache
from vinrec.models.release_information import TrackInfo
from vinrec.models.release_information import ImageInfo
from vinrec.models.release_information import ReleaseInfo
from vinrec.models.process import ProcessModel
from vinrec.models.process import ProcessSide

from vinrec.util.data_management import create_permanent_directories
from vinrec.const.locations import COVER_PATH

# Blueprint
app = Blueprint("release_information", "vinrec.views.release_information")

# Routes
@app.route("/search_discogs", methods=["GET", "POST"])
def search_discogs():
    if request.method == "GET":
        return render_template("release_information/search_discogs.html")
    
    else:
        query = request.form.get("query", None)
        if query is None:
            abort(422)

        sid, results = search(query)
        return redirect(url_for('release_information.discogs_results', sid=sid))
    
@app.route("/discogs_results/<sid>")
def discogs_results(sid):
    sid, results = SearchResultCache.get_by_id(sid)
    results = copy.deepcopy(results)
    for result in results:
        rid = result["uri"].split("/")[-1]
        result.update({"rid": rid})

        ri = ReleaseCache.get(rid)
        if ri is not None:
            result.update({
                "local_stored": True,
                "release_info": ri
            })
        
    return render_template("release_information/discogs_results.html", results=results)

@app.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "GET":
        releases = ReleaseInfo.select().where(ReleaseInfo.is_external == False).objects()
        return render_template("release_information/create.html", releases=releases)
    
    else:
        artist = request.form["artist"]
        title = request.form["title"]
        released = request.form["year"]
        genres = request.form["styles"]
        
        _genres = genres.split(",")
        genres = []
        for genre in _genres:
            _genre = genre.strip()
            if _genre != "":
                genres.append(_genre)
        print(genres)

        ri = ReleaseInfo(
            rid = str(uuid.uuid1()).replace("-", ""),
            is_external = False,

            artist = artist,
            title = title,
            genres = ';'.join(genres),
            released = int(released)
        )
        ri.save()

        track_index = 0
        while request.form.get("track_{0}_side".format(track_index), None) is not None:
            side = request.form["track_{0}_side".format(track_index)]
            track = int(request.form["track_{0}_track".format(track_index)])
            title = request.form["track_{0}_title".format(track_index)]
            track_index += 1

            ti = TrackInfo(
                duration=0,
                side = side,
                position = int(track),
                title  = title,
                release = ri
            )
            ti.save()

        return redirect(url_for('process.use_release', rid=ri.rid))

@app.route("/remove/<ref>")
@app.route("/remove/<ref>/<url>")
def remove(ref, url=None):
    print(ref, url)
    # Remove release from database
    ri = ReleaseCache.get(ref)
    for track in ri.get_tracks():
        track.delete_instance()
    for image in ri.get_images():
        image.delete_instance()
    
    for process in ProcessModel.select().where(ProcessModel.release==ri).objects():
        for side in ProcessSide.select().where(ProcessSide.process==process).objects():
            side.delete_instance()
        process.delete_instance()

    ri.delete_instance()
    if url is None:
        return redirect(url_for("index.index"))
    else:
        return redirect(url.replace("%2F", "/"))

@app.route("/check/<ref>")
def check_release(ref):
    release = load_release_info(ref)
    return render_template("release_information/check.html", release=release)

@app.route("/edit/<ref>", methods=["GET", "POST"])
def edit_release(ref):
    ri = ReleaseCache.get(ref)
    if request.method == "GET":
        return render_template("release_information/edit.html", release=ri)
    else:
        ri.artist = request.form.get("artist", ri.artist)
        ri.title = request.form.get("title", ri.title)
        ri.released = request.form.get("year", ri.released)

        genres = request.form.get("styles", None)
        if genres is not None:
            _genres = genres.split(",")
            genres = []
            for genre in _genres:
                _genre = genre.strip()
                if _genre != "":
                    genres.append(_genre)
            
            ri.genres = ';'.join(genres)
        
        ri.save()

        for track in TrackInfo.select().where(TrackInfo.release==ri):
            track.title = request.form.get("track_" + track.side + str(track.position), track.title)
            track.save()

        return redirect(url_for("process.use_release", rid=ref))

@app.route("/select_cover/<ref>", methods=["GET", "POST"])
def select_cover(ref):
    ri = ReleaseCache.get(ref)
    if request.method == "GET":
        return render_template("release_information/select_cover.html", release=ri)
    else:
        create_permanent_directories()
        fname = "{0}_{1}.jpeg".format(ri.rid, "uc")
        path = os.path.join(COVER_PATH, fname)
        if os.path.isfile(path):
            os.remove(path)
        f = request.files.get("cover_file")
        f.save(path)
        ri.cover_image = fname
        ri.save()        
        return redirect(url_for("process.use_release", rid=ri.rid))

@app.route("/use_cover/<release>/<cover>")
def use_cover(release, cover):
    ri = ReleaseCache.get(release)
    cover = ImageInfo.get_or_none(ImageInfo.iid==cover, ImageInfo.release==ri)
    fname = store_cover(ri, cover)
    ri.cover_image = fname
    ri.save()
    return redirect(url_for("process.use_release", rid=ri.rid))

templates/release_information/check.html
{% extends "base.html" %}
{% block title %}Check Release{% endblock %}

{% block main %}


<div class="row">
<div class="col-md-8">
<h2>{{ release.artist }} - {{ release.title }} ({{ release.released }})</h2>

<h2><a href="{{ url_for('process.use_release', rid=release.rid) }}" class="button">Use this release!</a></h2>
<h3><a href="{{ url_for('release_information.edit_release', ref=release.rid) }}" class="button">Edit this release!</a></h3>

<b>Styles:</b>
{% for genre in release.genres.split(";") %}{{ genre }}, {% endfor %}
<br><br>
<h5>Tracklist:</h5>
<div class="table-responsive col-md-12">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Pos</th>
                <th>Title</th>
                <th>Duration</th>
            </tr>
        </thead>
        <tbody>
            {% for track in release.get_tracks() %}
            <tr>
                <td>{{ track.side }}{{ track.position }}</td>
                <td>{{ track.title }}</td>
                <td>{{ track.duration }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

</div>
<div class="col-md-4">
Images:<br>
{% for image in release.get_images() %}
<img src="{{ image.thumb }}"/><br>
{% endfor %}
</div>
</div>

{% endblock %}

templates/release_information/create.html
{% extends "base.html" %}

{% block title %}Create Release Information{% endblock %}

{% block main %}
<h2> Create Release Information </h2>
<div class="container">
    <div class="row">

    <div class="col-md-8">
        <form action="{{ url_for('release_information.create') }}" method="POST">

            <div class="row">
                <div class="col-md-8">
                    <label for="artist" class="col-md-2">Artist: </label><input class="col-md-8" type="text" name="artist" placeholder="Artist"><br>
                    <label for="title" class="col-md-2">Title: </label><input class="col-md-8" type="text" name="title" placeholder="Title"><br>
                    <label for="year" class="col-md-2">Year: </label><input class="col-md-8" type="text" name="year" placeholder="YYYY" pattern="\d\d\d\d"><br>
                    <label for="styles" class="col-md-2">Styles: </label><input class="col-md-8" size=30 type="text" placeholder="Style, Style, Style" name="styles" value=""><br><br>
                </div>
            </div>
            <div class="row">   
                <div class="table-responsive col-md-12">
                    <h5>Tracklist:</h5>
                    <table class="table table-striped table-sm" id="tracktable">
                        <thead>
                            <tr>
                                <th>Side</th>
                                <th>Track</th>
                                <th>Title</th>
                                <th>Duration</th>
                            </tr>
                        </thead>
                        <tbody id="track_table_body">
                            
                        </tbody>
                    </table>
                    <a href="#" onclick="add_row();">Add Row</a><br>
                    <a href="#" onclick="rem_row();">Remove Row</a>
                </div>
            </div>
        <br><br><input type="submit" value="Save!">

        </form>
    </div>
    <div class="col-md-4">
        <h4>Available self-created releases</h4>
        <ul>
            {% for rel in releases %}
            <li> <a href="{{ url_for('release_information.edit_release', ref=rel.rid) }}">{{ rel.artist }} - {{ rel.title }} ({{ rel.released }})</a></li>
            {% endfor %}
        </ul>
    </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script>

    function add_row(){
        var table = document.getElementById("tracktable");
        var row = table.insertRow();
        var row_count = table.rows.length - 2;
        row.innerHTML = `
        <tr>
            <td><select name="track_` + row_count + `_side">
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
                <option value="F">F</option>
            </select></td>
            <td><input type="number" name="track_` + row_count + `_track" value=1></td>
            <td><input type="text" name="track_` + row_count + `_title" placeholder="Title"></td>
            <td>--:--   </td>
        </tr>
        `
    }
    function rem_row(){
        var table = document.getElementById("tracktable");
        table.deleteRow(-1);
    }
</script>
{% endblock %}

templates/release_information/discogs_results.html
{% extends "base.html" %}
{% block title %} Search Results {% endblock %}

{% block main %}
<h2>Search Results</h2>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Artist</th>
                <th>Title</th>
                <th>Format</th>
                <th>Discogs Ref</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for e in results %}
            {% if e.type == "Release" %}
            <tr>
                <td><a href="{{ url_for('release_information.check_release', ref=e.rid) }}">Details  </a></td>
                
                {% if e.local_stored %}
                    <td>{{ e.release_info.artist }}</td>
                    <td>{{ e.release_info.title }}</td>
                {% else %}
                    <td>{{ e.artist }}</td>
                    <td>{{ e.title }}</td>
                {% endif %}

                <td>{{ e.format }}</td>
                <td>{{ e.rid }}</td>
                
                {% if e.local_stored %}
                    <td><a href="#" onclick="delete_release({{ e.rid }});">Delete from local database</a></td>
                {% else %}
                    <td></td>
                {% endif %}
            
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>

    </table>
</div>

<script>
    function delete_release(ref){
        url = "{{ url_for('release_information.remove', ref='replace_this') }}".replace('replace_this', ref);
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.open( "GET", url, false ); // false for synchronous request
        xmlHttp.send( null );
        window.location.reload();
    }
</script>
{% endblock %}

templates/release_information/edit.html
{% extends "base.html" %}
{% block title %}Edit Release{% endblock %}

{% block main %}


<div class="row">
<div class="col-md-8">
<h2>Edit Release</h2>
<form action="{{ url_for('release_information.edit_release', ref=release.rid) }}" method="POST">
    <input type="text" placeholder="Artist" name="artist" value="{{ release.artist }}">
    <input type="text" placeholder="Title" name="title" value="{{ release.title }}">
    <input type="text" placeholder="Year" name="year" value="{{ release.released }}"><br>

    <b>Styles:</b>

    <input type="text" placeholder="Style, Style, Style" name="styles" value="{% for genre in release.genres.split(';') %}{{ genre }}, {% endfor %}">
    <br><br>
    <h5>Tracklist:</h5>
        
    <div class="table-responsive col-md-12">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Pos</th>
                    <th>Title</th>
                    <th>Duration</th>
                </tr>
            </thead>
            <tbody>
                {% for track in release.get_tracks() %}
                <tr>
                    <td>{{ track.side }}{{ track.position }}</td>
                    <td><input style="width: 90%;" placeholder="{{ track.side }}{{ track.position }} Title" type="text" name="track_{{ track.side }}{{ track.position }}" value="{{ track.title }}"></td>
                    <td>{{ track.duration }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <input type="submit" value="Save and use!">
    <a href="{{ url_for('release_information.remove', ref=release.rid) }}">Remove release</a>
</div>
<div class="col-md-4">
Images:<br>
{% for image in release.get_images() %}
<img src="{{ image.thumb }}"/><br>
{% endfor %}
</div>
</div>

{% endblock %}

templates/release_information/search_discogs.html
{% extends "base.html" %}

{% block title %} Search Discogs Data {% endblock %}

{% block main %}

<h3>Query:</h3>
<form method="POST" action="{{ url_for('release_information.search_discogs') }}">
    <input class="form-control input-lg" type="text" name="query" placeholder="Search query, e.g. barcode or artist and album name"><br>
    <input type="submit" value="Go!">
</form>


{% endblock %}

templates/release_information/select_cover.html
{% extends "base.html" %}
{% block title %}Select Cover Image{% endblock %}

{% block main %}

<h2>Select Cover Image</h2>

<div class="container">
<div class="row">
    <div class="container">
        <h3>Upload Own Image</h3>
    </div>
    <div class="col-md-12">
        <form action="{{ url_for('release_information.select_cover', ref=release.rid) }}" method="POST" enctype="multipart/form-data">
            <input type="file" name="cover_file">
            <input type="submit" value="Upload!">
        </form>
    </div>
</div>
{% if release.is_external %}
<br><br>
<div class="row">
    <div class="container">
        <h3>Discogs Images</h3>
    </div>
    {% for image in release.get_images() %}
    <div class="col-md-4">
        {# {{ image.id }} #}
        <a href="{{ url_for('release_information.use_cover', release=release.rid, cover=image.iid) }}"><img style="width: 100%;" src="{{ image.full }}"/></a>
    </div>
    {% endfor %}
</div>
{% endif %}
</div>

{% endblock %}