vinrec/views/index.py
# Flask imports
from flask import Blueprint
from flask import render_template
from flask import session
from flask import redirect
from flask import url_for

# Local imports
from vinrec.util.data_management import get_finished_records
from vinrec.util.data_management import get_unfinished_records

# Blueprint
app = Blueprint("index", "vinrec.views.index")

# Routes
@app.route("/")
def index():
    return render_template("index.html")

@app.route("/theme/<value>/<url>")
def theme(value, url):
    if value not in ("dark", "bright"):
        raise Exception("TODO: Error handling: Unknown theme")
    else:
        session["theme"] = value
        return redirect(url.replace("%2F", "/"))

vinrec/views/recorder.py
# Flask imports
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import jsonify

# Global imports
from werkzeug.utils import secure_filename
import os
import subprocess
import ffmpeg
import time

# Local imports
from vinrec.util.data_management import create_permanent_directories
from vinrec.const import locations
from vinrec.const import formats
from vinrec.util.recorder import Recorder

# Blueprint
app = Blueprint("recorder", "vinrec.views.recorder")

# Routes
@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        instance = Recorder.get_instance()
        status = "not_recording"
        if instance is not None:
            if instance.running is False and instance.process is not None:
                Recorder.clear_instance()
            else:
                status = "recording"

        return render_template("recorder/index.html", status=status, instance=instance)

    elif request.method == "POST":

        action = request.form.get("action", None)
        if action == "start_record":
            instance = Recorder.get_instance()
            if instance is None:
                name = request.form.get("name", None)
                if len(name.strip()) == 0: name = None
                Recorder(name=name).start()

        if action == "stop_record":
            instance = Recorder.get_instance()
            if instance is not None:
                instance.stop()
                while instance.running:
                    time.sleep(0.1)

        return redirect(url_for("recorder.index"))

@app.route("/status")
def status():
    instance = Recorder.get_instance()
    if instance is None:
        return jsonify({
            "error": "Recorder isn't running"
        })

    status = instance.get_status()
    return jsonify(status)


@app.route("/delete/<name>")
def delete(name):
    name = secure_filename(name)
    filename = "{0}.{1}".format(name, formats.WORK_FORMAT)
    if filename in os.listdir(locations.UNFINISHED_RECORDS):
        os.remove(os.path.join(locations.UNFINISHED_RECORDS, filename))
    return redirect(url_for("index.index"))

vinrec/views/release_information.py
# Flask imports
from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import url_for
from flask import request
from flask import abort

# Global imports
import os
import copy
import uuid

# Local imports
from vinrec.util.discogs import search
from vinrec.util.discogs import SearchResultCache
from vinrec.util.discogs import load_release_info
from vinrec.util.discogs import store_cover
from vinrec.models.release_information import ReleaseCache
from vinrec.models.release_information import TrackInfo
from vinrec.models.release_information import ImageInfo
from vinrec.models.release_information import ReleaseInfo
from vinrec.models.process import ProcessModel
from vinrec.models.process import ProcessSide

from vinrec.util.data_management import create_permanent_directories
from vinrec.const.locations import COVER_PATH

# Blueprint
app = Blueprint("release_information", "vinrec.views.release_information")

# Routes
@app.route("/search_discogs", methods=["GET", "POST"])
def search_discogs():
    if request.method == "GET":
        return render_template("release_information/search_discogs.html")
    
    else:
        query = request.form.get("query", None)
        if query is None:
            abort(422)

        sid, results = search(query)
        return redirect(url_for('release_information.discogs_results', sid=sid))
    
@app.route("/discogs_results/<sid>")
def discogs_results(sid):
    sid, results = SearchResultCache.get_by_id(sid)
    results = copy.deepcopy(results)
    for result in results:
        rid = result["uri"].split("/")[-1]
        result.update({"rid": rid})

        ri = ReleaseCache.get(rid)
        if ri is not None:
            result.update({
                "local_stored": True,
                "release_info": ri
            })
        
    return render_template("release_information/discogs_results.html", results=results)

@app.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "GET":
        releases = ReleaseInfo.select().where(ReleaseInfo.is_external == False).objects()
        return render_template("release_information/create.html", releases=releases)
    
    else:
        artist = request.form["artist"]
        title = request.form["title"]
        released = request.form["year"]
        genres = request.form["styles"]
        
        _genres = genres.split(",")
        genres = []
        for genre in _genres:
            _genre = genre.strip()
            if _genre != "":
                genres.append(_genre)
        print(genres)

        ri = ReleaseInfo(
            rid = str(uuid.uuid1()).replace("-", ""),
            is_external = False,

            artist = artist,
            title = title,
            genres = ';'.join(genres),
            released = int(released)
        )
        ri.save()

        track_index = 0
        while request.form.get("track_{0}_side".format(track_index), None) is not None:
            side = request.form["track_{0}_side".format(track_index)]
            track = int(request.form["track_{0}_track".format(track_index)])
            title = request.form["track_{0}_title".format(track_index)]
            track_index += 1

            ti = TrackInfo(
                duration=0,
                side = side,
                position = int(track),
                title  = title,
                release = ri
            )
            ti.save()

        return redirect(url_for('process.use_release', rid=ri.rid))

@app.route("/remove/<ref>")
@app.route("/remove/<ref>/<url>")
def remove(ref, url=None):
    print(ref, url)
    # Remove release from database
    ri = ReleaseCache.get(ref)
    for track in ri.get_tracks():
        track.delete_instance()
    for image in ri.get_images():
        image.delete_instance()
    
    for process in ProcessModel.select().where(ProcessModel.release==ri).objects():
        for side in ProcessSide.select().where(ProcessSide.process==process).objects():
            side.delete_instance()
        process.delete_instance()

    ri.delete_instance()
    if url is None:
        return redirect(url_for("index.index"))
    else:
        return redirect(url.replace("%2F", "/"))

@app.route("/check/<ref>")
def check_release(ref):
    release = load_release_info(ref)
    return render_template("release_information/check.html", release=release)

@app.route("/edit/<ref>", methods=["GET", "POST"])
def edit_release(ref):
    ri = ReleaseCache.get(ref)
    if request.method == "GET":
        return render_template("release_information/edit.html", release=ri)
    else:
        ri.artist = request.form.get("artist", ri.artist)
        ri.title = request.form.get("title", ri.title)
        ri.released = request.form.get("year", ri.released)

        genres = request.form.get("styles", None)
        if genres is not None:
            _genres = genres.split(",")
            genres = []
            for genre in _genres:
                _genre = genre.strip()
                if _genre != "":
                    genres.append(_genre)
            
            ri.genres = ';'.join(genres)
        
        ri.save()

        for track in TrackInfo.select().where(TrackInfo.release==ri):
            track.title = request.form.get("track_" + track.side + str(track.position), track.title)
            track.save()

        return redirect(url_for("process.use_release", rid=ref))

@app.route("/select_cover/<ref>", methods=["GET", "POST"])
def select_cover(ref):
    ri = ReleaseCache.get(ref)
    if request.method == "GET":
        return render_template("release_information/select_cover.html", release=ri)
    else:
        create_permanent_directories()
        fname = "{0}_{1}.jpeg".format(ri.rid, "uc")
        path = os.path.join(COVER_PATH, fname)
        if os.path.isfile(path):
            os.remove(path)
        f = request.files.get("cover_file")
        f.save(path)
        ri.cover_image = fname
        ri.save()        
        return redirect(url_for("process.use_release", rid=ri.rid))

@app.route("/use_cover/<release>/<cover>")
def use_cover(release, cover):
    ri = ReleaseCache.get(release)
    cover = ImageInfo.get_or_none(ImageInfo.iid==cover, ImageInfo.release==ri)
    fname = store_cover(ri, cover)
    ri.cover_image = fname
    ri.save()
    return redirect(url_for("process.use_release", rid=ri.rid))

vinrec/views/upload.py
# Flask imports
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for

# Global imports
from werkzeug.utils import secure_filename
import os
import ffmpeg

# Local imports
from vinrec.util.data_management import create_permanent_directories
from vinrec.util.data_management import create_temporary_directories
from vinrec.util.data_management import clear_temporary_directories
from vinrec.const import locations

# Blueprint
app = Blueprint("upload", "vinrec.views.upload")

# Routes
@app.route("/record", methods=["GET", "POST"])
def record():
    if request.method == "GET":
        return render_template("upload/record.html")

    elif request.method == "POST":

        create_permanent_directories()
        create_temporary_directories()

        # Save and convert all files
        files = request.files.getlist("files")
        for f in files:
            # Save file to temporary directory
            filename = secure_filename(f.filename)
            path = os.path.join(locations.TMP, filename)
            f.save(path)

            # Convert file and write to permanent directory
            input_path = path
            new_filename = '.'.join(filename.split(".")[:-1]) + ".wav" # Change file extension to .wav
            output_path = os.path.join(locations.UNFINISHED_RECORDS, new_filename)
            (
                ffmpeg
                .input(input_path)
                .output(output_path)
                .run(overwrite_output=True)
            )

        clear_temporary_directories()

        return redirect(url_for("index.index"))

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}">

    {% block head %}
    {% endblock %}

    <title>{% block title %}{% endblock %} - VinRec</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
    {% if session['theme'] %}
        {% if session['theme'] == 'bright' %}
            {% set theme_name = 'default' %}
        {% else %}
            {% set theme_name = 'darkly' %}
        {% endif %}
    {% else %}
        {% set theme_name = 'darkly' %}
    {% endif %}
    {% set theme_path = 'css/themes/' ~ theme_name ~ '/bootstrap.min.css' %}
    <link href="{{ url_for('static', filename=theme_path) }}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet">
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/"><img style="max-height: 2rem; margin-right: 0.5rem;" src="{{ url_for('static', filename='img/favicon.png') }}"> VinRec</a>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if request.endpoint=='index.index' %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('index.index') }}">Home</a>
          </li>
          <li class="nav-item {% if request.endpoint=='data.index' %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('data.index') }}">Data Manager</a>
          </li>
          {% block navbar_items %}
          {% endblock %}
        </ul>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <h1 class="mt-5">{% block heading %}{% endblock %}</h1>
      {% block main %}
      {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="footer bg-dark">
      <div class="container">
        <span class="text-muted">VinRec (C) 2019 - 2020 Ole Lange - View <a href="https://github.com/olell/VinRec" target="_blank">Source</a> on Github</span>

        <span class="float-right">
            {% if session['theme'] == 'bright' %}
            <a href="{{ url_for('index.theme', value='dark', url=request.path.replace('/', '%2F')) }}"> Dark </a>
            {% else %}
            <a href="{{ url_for('index.theme', value='bright', url=request.path.replace('/', '%2F')) }}"> Bright </a>
            {% endif %}
        </span>
      </div>
    </footer>


    <script src="{{ url_for('static', filename='js/jquery.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    {% block scripts %}
    {% endblock %}

  </body>
</html>

templates/base.jinja
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}">

    {% block head %}
    {% endblock %}

    <title>{% block title %}{% endblock %} - VinRec</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
    {% if session['theme'] %}
        {% if session['theme'] == 'bright' %}
            {% set theme_name = 'united' %}
        {% else %}
            {% set theme_name = 'darkly' %}
        {% endif %}
    {% else %}
        {% set theme_name = 'darkly' %}
    {% endif %}
    {% set theme_path = 'css/themes/' ~ theme_name ~ '/bootstrap.min.css' %}
    <link href="{{ url_for('static', filename=theme_path) }}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet">
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/"><img style="max-height: 2rem; margin-right: 0.5rem;" src="{{ url_for('static', filename='img/favicon.png') }}"> VinRec</a>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('index.index') }}">Home</a>
          </li>
          {% block navbar_items %}
          {% endblock %}
        </ul>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <h1 class="mt-5">{% block heading %}{% endblock %}</h1>
      {% block main %}
      {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="footer bg-dark">
      <div class="container">
        <span class="text-muted">VinRec (C) 2019 Ole Lange - View <a href="https://github.com/olell/VinRec">Source</a> on Github</span>

        <span class="float-right">
            {% if session['theme'] == 'bright' %}
            <a href="{{ url_for('index.theme', value='dark') }}"> Dark </a>
            {% else %}
            <a href="{{ url_for('index.theme', value='bright') }}"> Bright </a>
            {% endif %}
        </span>
      </div>
    </footer>


    <script src="{{ url_for('static', filename='js/jquery.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    {% block scripts %}
    {% endblock %}

  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block main %}

<div class="container">

    <div class="row">

        {# Showing a step by step workflow on the left side #}
        <div class="col-md-6">
            <h2> Start Digitizing </h2>
            <br>
            <h4> Audio Files </h4>
            <div class="ml-3">
                Do you want to create <a class="font-weight-bold" href="{{ url_for('recorder.index') }}">new audio files by recording them</a><br>
                Or do you want to <a href="{{ url_for('upload.record') }}">upload existing audio files</a>
            </div>
            <br>
            <h4> Process your files </h4>
            <div class="ml-3">
                Do you want to <a class="font-weight-bold" href="{{ url_for('release_information.search_discogs') }}"> search your record in the discogs database </a><br>
                Or do you want to <a href="{{ url_for('release_information.create') }}">enter custom information about your record</a>
            </div>
        </div>

        {# Showing a list of finished records on the right side #}
        <div class="col-md-6">
            <h2> Stored Data </h2>
            <br>
            <h4> Data Manager </h4>
            <a href="{{ url_for('data.index') }}"><b>Manage locally stored data</b></a><br>
    </div>

</div>

{% endblock %}

templates/index.jinja
{% extends "base.jinja" %}

{% block title %} Home {% endblock %}

{% block main %}

<div class="container">

    <div class="row">

        {# Showing a step by step workflow on the left side #}
        <div class="col-md-6">
            <h2> Start Digitizing </h2>
            <br>
            <h4> Audio Files </h4>
            <div class="ml-3">
                Do you want to create <a class="font-weight-bold" href="{{ url_for('recorder.index') }}">new audio files by recording them</a><br>
                Or do you want to <a href="{{ url_for('upload.record') }}">upload existing audio files</a>
            </div>
            <br>
            <h4> Process your files </h4>
            <div class="ml-3">
                Do you want to <a class="font-weight-bold" href="#"> search your record in the discogs database </a><br>
                Or do you want to <a href="#">enter custom information about your record</a>
            </div>
        </div>

        {# Showing a list of finished records on the right side #}
        <div class="col-md-6">
            <h2> Stored Data </h2>
            <br>
            <h4> Finished Records </h4>
            {% if finished_records|length == 0 %}
                <div class="ml-3">
                -
                </div>
            {% else %}
            <ul>
            {% for record in finished_records %}
                <li> <a href="#"> {{ record.name }} </a></li> {# TODO: Link #}
            {% endfor %}
            </ul>
            {% endif %}
            <br>
            <h4> Stored Audio Files </h4>
            {% if unfinished_records|length == 0 %}
                <div class="ml-3">
                -
                </div>
            {% else %}
            <ul>
            {% for record in unfinished_records %}
                <li> {{ record }} (<a href="{{ url_for('recorder.delete', name=record) }}">Remove</a>) </li>
            {% endfor %}
            </ul>
            {% endif %}
        </div>

    </div>

</div>

{% endblock %}