vinrec/views/recorder.py
# Flask imports
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import jsonify

# Global imports
from werkzeug.utils import secure_filename
import os
import subprocess
import ffmpeg
import time

# Local imports
from vinrec.util.data_management import create_permanent_directories
from vinrec.const import locations
from vinrec.const import formats
from vinrec.util.recorder import Recorder

# Blueprint
app = Blueprint("recorder", "vinrec.views.recorder")

# Routes
@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "GET":
        instance = Recorder.get_instance()
        status = "not_recording"
        if instance is not None:
            if instance.running is False and instance.process is not None:
                Recorder.clear_instance()
            else:
                status = "recording"

        return render_template("recorder/index.html", status=status, instance=instance)

    elif request.method == "POST":

        action = request.form.get("action", None)
        if action == "start_record":
            instance = Recorder.get_instance()
            if instance is None:
                name = request.form.get("name", None)
                if len(name.strip()) == 0: name = None
                Recorder(name=name).start()

        if action == "stop_record":
            instance = Recorder.get_instance()
            if instance is not None:
                instance.stop()
                while instance.running:
                    time.sleep(0.1)

        return redirect(url_for("recorder.index"))

@app.route("/status")
def status():
    instance = Recorder.get_instance()
    if instance is None:
        return jsonify({
            "error": "Recorder isn't running"
        })

    status = instance.get_status()
    return jsonify(status)


@app.route("/delete/<name>")
def delete(name):
    name = secure_filename(name)
    filename = "{0}.{1}".format(name, formats.WORK_FORMAT)
    if filename in os.listdir(locations.UNFINISHED_RECORDS):
        os.remove(os.path.join(locations.UNFINISHED_RECORDS, filename))
    return redirect(url_for("index.index"))

templates/recorder/index.html
{% extends "base.html" %}

{% block head %}
<script src="{{ url_for('static', filename='js/chart.min.js') }}"></script>
{% endblock %}

{% block title %} Recorder {% endblock %}

{% block main %}

{% if status == 'not_recording' %}

<h1> Recorder </h1>

<form action="{{ url_for('recorder.index') }}" method="POST" class="col-md-6">
    <input type="hidden" name="action" value="start_record">
    <input type="text"  name="name" placeholder="Record name"><br><br>
    
    <input type="submit" value="Start Recorder">
</form>

{% elif status == 'recording' %}

<h1 > Recording "{{ instance.name }}" </h1>

<form action="{{ url_for('recorder.index') }}" method="POST">
    <input type="hidden" name="action" value="stop_record">
    <input type="submit" value="Stop Recorder">
</form>

<h2 id="record_length"></h2>

<div class="container col-md-12">
<div class="row col-md-12">
    <div class="col-md-8">
        <canvas id="canvas"></canvas>
    </div>
</div>
</div>

<script>

var chart = null;

function update_status(){
    var xhr = new XMLHttpRequest();

    xhr.addEventListener('readystatechange', function(event) {
        if (event.target.readyState == 4 && event.target.responseText) {
            var status = JSON.parse(event.target.responseText);

            var minutes = (status.record_length / 1000) / 60;
            var seconds = Math.floor((minutes - Math.floor(minutes)) * 60);
            minutes = Math.floor(minutes);

            minutes = String(minutes);
            seconds = String(seconds);

            if (minutes.length < 2) {
                minutes = "0" + minutes;
            }
            if (seconds.length < 2) {
                seconds = "0" + seconds;
            }

            document.getElementById("record_length").innerText = "Record length: " + minutes + ":" + seconds;

            chart.data = {
                labels: status.times,
                datasets: [{
                    data: status.waveform,
                    label: "Waveform",
                    borderColor: "#3e95cd",
                    fill: false
                }]
            };
            chart.update();
        }
    }, false);

    xhr.open("GET", "{{ url_for('recorder.status') }}", true);
    xhr.send();
}


window.onload = function() {

    chart = new Chart(document.getElementById("canvas"), {
        type: 'line',
        data: {},
        options: {
            title: {
            display: true,
            text: 'Waveform'
            },
            animation: false,
            scales: {
                yAxes: [{
                    ticks: {
                        suggestedMin: -1,
                        suggestedMax: 1
                    }
                }]
            },
            bezierCurve: false
        }
    });


    update_status();
    setInterval(update_status, 500);
}

</script>


{% endif %}

{% endblock %}

templates/recorder/index.jinja
{% extends "base.jinja" %}

{% block head %}
<script src="{{ url_for('static', filename='js/chart.min.js') }}"></script>
{% endblock %}

{% block title %} Recorder {% endblock %}

{% block main %}

{% if status == 'not_recording' %}

<h1> Recorder </h1>

<form action="{{ url_for('recorder.index') }}" method="POST" class="col-md-6">
    <input type="hidden" name="action" value="start_record">
    <input type="text"  name="name" placeholder="Record name"><br><br>
    Sample Rate:<br>
    <select name="rate">
        <option value="8000">8 kHz</option>
        <option value="44100">44.1 kHz</option>
        <option value="48000">48 kHz</option>
        <option value="96000">96 kHz</option>
        <option value="192000" selected>192 kHz (recommended)</option>
        <option value="384000">384 kHz</option>
    </select><br>
    Format: <br>
    <select name="format">
        <option value="S16_LE">16-Bit</option>
        <option value="S24_LE">24-Bit</option>
        <option value="S32_LE" selected>32-Bit</option>
    </select>
    <br><br><br>
    <input type="submit" value="Start Recorder">
</form>

{% elif status == 'recording' %}

<h1 > Recording "{{ instance.name }}" </h1>

<form action="{{ url_for('recorder.index') }}" method="POST">
    <input type="hidden" name="action" value="stop_record">
    <input type="submit" value="Stop Recorder">
</form>

<h2 id="record_length"></h2>

<div class="container col-md-12">
<div class="row col-md-12">
    <div class="col-md-8">
        <canvas id="canvas"></canvas>
    </div>
</div>
</div>

<script>

var chart = null;

function update_status(){
    var xhr = new XMLHttpRequest();

    xhr.addEventListener('readystatechange', function(event) {
        if (event.target.readyState == 4 && event.target.responseText) {
            var status = JSON.parse(event.target.responseText);

            var minutes = (status.record_length / 1000) / 60;
            var seconds = Math.floor((minutes - Math.floor(minutes)) * 60);
            minutes = Math.floor(minutes);

            minutes = String(minutes);
            seconds = String(seconds);

            if (minutes.length < 2) {
                minutes = "0" + minutes;
            }
            if (seconds.length < 2) {
                seconds = "0" + seconds;
            }

            document.getElementById("record_length").innerText = "Record length: " + minutes + ":" + seconds;

            chart.data = {
                labels: status.times,
                datasets: [{
                    data: status.waveform,
                    label: "Waveform",
                    borderColor: "#3e95cd",
                    fill: false
                }]
            };
            chart.update();
        }
    }, false);

    xhr.open("GET", "{{ url_for('recorder.status') }}", true);
    xhr.send();
}


window.onload = function() {

    chart = new Chart(document.getElementById("canvas"), {
        type: 'line',
        data: {},
        options: {
            title: {
            display: true,
            text: 'Waveform'
            },
            animation: false,
            scales: {
                yAxes: [{
                    ticks: {
                        suggestedMin: 0,
                        suggestedMax: 1
                    }
                }]
            },
            bezierCurve: false
        }
    });


    update_status();
    setInterval(update_status, 500);
}

</script>


{% endif %}

{% endblock %}